sudo: required

services:
   - docker

before_install:
   - docker build -t amose/docker-react-sample -f Dockerfile.dev .
   
script:
   - docker run amose/docker-react-sample npm run test -- --coverage   